# Generated by Django 4.1.7 on 2023-05-27 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dscription', models.TextField()),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
