# Generated by Django 4.1.7 on 2023-05-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dscription',
            new_name='description',
        ),
    ]
