# Generated by Django 4.1.7 on 2023-07-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile',
            field=models.ImageField(null=True, upload_to='users_profile'),
        ),
    ]
